server:
  port: :8080
  app_base_url: "http://localhost"

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: apartment_db

telegram_config:
  bot_token: ""
  timeout: 30s
  webhook: ""
  maxconnections: 5